In [1]:
import numpy as np

In [2]:
matrix_B = np.array([[[1,1,2,3,4], [4,1,3,7,2], [9,4,6,1,4]]])

In [3]:
matrix_B

array([[[1, 1, 2, 3, 4],
        [4, 1, 3, 7, 2],
        [9, 4, 6, 1, 4]]])

In [4]:
print(matrix_B[::2])

[[[1 1 2 3 4]
  [4 1 3 7 2]
  [9 4 6 1 4]]]
